// examples/vue-demo/src/App.vue
<script setup lang="ts">
import { useLumina } from '@continuouslabs/lumina-vue'

/**
 * Lumina Vue Demo
 * Showcasing Composition API integration with zero-config i18n.
 */
const { locale, setLocale } = useLumina()
const name = 'Felix'
</script>

<template>
  <div class="card">
    <div class="badge" t>Vue + Lumina</div>
    
    <!-- 
      The 't' attribute works exactly the same in Vue templates! 
      The SWC compiler transforms this into a reactive getText call.
    -->
    <h1 t>Build multilingual apps in seconds, not hours.</h1>
    
    <p t>Hey {name}, welcome to the Vue demo. Change the language below and watch the reactivity in action.</p>
    
    <div class="controls">
      <button 
        @click="setLocale('en')" 
        :class="{ secondary: locale !== 'en' }"
      >
        English
      </button>
      <button 
        @click="setLocale('es')" 
        :class="{ secondary: locale !== 'es' }"
      >
        Español
      </button>
    </div>
    
    <div style="margin-top: 2rem; opacity: 0.5; font-size: 0.9rem">
      <span t>Selected Locale:</span> {{ locale }}
    </div>
  </div>
</template>

<style scoped>
/* Scoped styles can be added here, but we use the global index.css for the premium look */
</style>

// examples/react-demo/src/App.tsx
import React from 'react'
import { LuminaProvider, useLumina } from '@continuouslabs/lumina-react'
/**
 * Lumina Demo Application
 * This showcase demonstrates zero-config i18n with premium UI.
 */
function Dashboard() {
  const { locale, setLocale } = useLumina()
  const name = 'Felix'

  return (
    <div className="card">
      <div className="badge" t>Premium Experience</div>
      
      {/* 
        Note: The 't' attribute is detected by the SWC compiler 
        and replaced with reactive signals. No manual translations needed!
      */}
      <h1 t>Internationalization has never been this easy.</h1>
      
      {/* Interpolation is handled naturally */}
      <p t>Welcome back to your workspace, {name}. Lumina detected your environment and loaded the perfect locale for you.</p>
      
      <div className="controls">
        <button onClick={() => setLocale('en')} className={locale === 'en' ? '' : 'secondary'}>
          English
        </button>
        <button onClick={() => setLocale('es')} className={locale === 'es' ? '' : 'secondary'}>
          Español
        </button>
      </div>
      
      <div style={{ marginTop: '2rem', opacity: 0.5, fontSize: '0.9rem' }}>
        <span t>Current Locale:</span> {locale}
      </div>
    </div>
  )
}

function App() {
  return (
    <LuminaProvider>
      <Dashboard />
    </LuminaProvider>
  )
}

export default App
